language: scala
scala:
   - 2.11.11
   - 2.12.3
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
script:
  - ./sbt ++$TRAVIS_SCALA_VERSION jacoco:cover
  - ./siva-unpack ./src/test/resources/basic.siva ./basic-unpacked
after_success:
  - bash <(curl -s https://codecov.io/bash)