#!/bin/bash

# Convenience script to unpack a siva file using JVM native java-siva

fatjar="target/scala-2.11/siva-java-assembly-0.1.0-SNAPSHOT.jar"
build_command="./sbt assembly"

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }

if [[ ! -f "${fatjar}" ]]; then
    echo "${fatjar} not found. Running build ${build_command}"
    $build_command
fi

exec java -jar "${fatjar}" $@